[package]
name = "ui_adapter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sln_operations = { version = "0.1.0", path = "../sln_operations" }
